INSERT INTO tb_caracteristica(ds_caracteristica, ds_especifico) VALUES
									('TIPO-CARNE', 'CARNE-BOVINA'),
									('TIPO-CARNE', 'CARNE-SUINA'),
									('TIPO-CARNE', 'PEIXES-AGUA-SALGADA'),
                                    ('TIPO-CARNE', 'PEIXES-AGUA-DOCE'),
                                    ('TIPO-CARNE', 'AVES'),
                                    ('CARNE-BOVINA','Acém'),
									('CARNE-BOVINA','Alcatra'),
									('CARNE-BOVINA','Capa de filé'),
									('CARNE-BOVINA','Contra filé'),
									('CARNE-BOVINA','Coxão duro'),
									('CARNE-BOVINA','Coxão mole'),
									('CARNE-BOVINA','Cupim'),
									('CARNE-BOVINA','Filé de costela'),
									('CARNE-BOVINA','Filé-mignon'),
									('CARNE-BOVINA','Fraldinha'),
									('CARNE-BOVINA','Lagarto'),
									('CARNE-BOVINA','Maminha'),
									('CARNE-BOVINA','Músculo dianteiro'),
									('CARNE-BOVINA','Músculo traseiro'),
									('CARNE-BOVINA','Paleta'),
									('CARNE-BOVINA','Patinho'),
									('CARNE-BOVINA','Peito'),
									('CARNE-BOVINA','Pescoço'),
									('CARNE-BOVINA','Picanha'),
									('CARNE-BOVINA','Ponta de agulha'),
                                    ('CARNE-SUINA','Bisteca'),
									('CARNE-SUINA','Filé Mignon'),
									('CARNE-SUINA','Suã'),
									('CARNE-SUINA','Lombo'),
									('CARNE-SUINA','Maminha'),
									('CARNE-SUINA','Paleta'),
									('CARNE-SUINA','Papada'),
									('CARNE-SUINA','T-Bone'),
									('CARNE-SUINA','Lombo Inglês'),
									('CARNE-SUINA','Copa-lombo'),
									('CARNE-SUINA','Pancetta'),
									('CARNE-SUINA','Pernil'),
									('CARNE-SUINA','Ossobuco'),
									('CARNE-SUINA','Alcatra'),
									('CARNE-SUINA','Máscara'),
									('CARNE-SUINA','Joelho'),
									('CARNE-SUINA','Prime Rib'),
									('CARNE-SUINA','Barriga'),
									('CARNE-SUINA','Coxão duro'),
									('CARNE-SUINA','Pé Dianteiro'),
									('CARNE-SUINA','Fraldinha'),
									('CARNE-SUINA','Costela'),
									('CARNE-SUINA','Picanha'),
									('CARNE-SUINA','Rabo'),
									('CARNE-SUINA','Orelha'),
									('CARNE-SUINA','Ribeye'),
									('CARNE-SUINA','Carré'),
                                    ('PEIXES-AGUA-SALGADA', 'Agulha'),
									('PEIXES-AGUA-SALGADA', 'Anchova'),
									('PEIXES-AGUA-SALGADA', 'Atum'),
									('PEIXES-AGUA-SALGADA', 'Bacalhau'),
									('PEIXES-AGUA-SALGADA', 'Badejo'),
									('PEIXES-AGUA-SALGADA', 'Cavala'),
									('PEIXES-AGUA-SALGADA', 'Dourado '),
									('PEIXES-AGUA-SALGADA', 'Garoupa'),
									('PEIXES-AGUA-SALGADA', 'Linguado'),
									('PEIXES-AGUA-SALGADA', 'Manjuba'),
									('PEIXES-AGUA-SALGADA', 'Merluza'),
									('PEIXES-AGUA-SALGADA', 'Pargo'),
									('PEIXES-AGUA-SALGADA', 'Peixe-espada'),
									('PEIXES-AGUA-SALGADA', 'Pescada'),
									('PEIXES-AGUA-SALGADA', 'Polaca do Alasca'),
									('PEIXES-AGUA-SALGADA', 'Porquinho'),
									('PEIXES-AGUA-SALGADA', 'Robalo'),
									('PEIXES-AGUA-SALGADA', 'Salmão'),
									('PEIXES-AGUA-SALGADA', 'Sardinha'),
									('PEIXES-AGUA-DOCE', 'Carpa'),
									('PEIXES-AGUA-DOCE', 'Corvina'),
									('PEIXES-AGUA-DOCE', 'Curimbatá'),
									('PEIXES-AGUA-DOCE', 'Dourado de rio'),
									('PEIXES-AGUA-DOCE', 'Lambari'),
									('PEIXES-AGUA-DOCE', 'Matrinxã'),
									('PEIXES-AGUA-DOCE', 'Pacu'),
									('PEIXES-AGUA-DOCE', 'Panga'),
									('PEIXES-AGUA-DOCE', 'Pintado'),
									('PEIXES-AGUA-DOCE', 'Piramutaba'),
									('PEIXES-AGUA-DOCE', 'Pirarucu'),
									('PEIXES-AGUA-DOCE', 'Tambaqui'),
									('PEIXES-AGUA-DOCE', 'Tilápia'),
									('PEIXES-AGUA-DOCE', 'Traíra'),
									('PEIXES-AGUA-DOCE', 'Truta'),
									('PEIXES-AGUA-DOCE', 'Tucunaré'),
                                    ('AVES','Peito'),
									('AVES','Asas'),
									('AVES','coxa'),
									('AVES','Sobrecoxa'),
									('AVES','Miúdos'),
									('AVES','Coração');

																													
																				