INSERT INTO tb_caracteristica(ds_caracteristica, ds_especifico) VALUES
									('TIPO-CARNE', 'CARNE-BOVINA'),
									('TIPO-CARNE', 'CARNE-SUINA'),
									('TIPO-CARNE', 'PEIXES-AGUA-SALGADA'),
                                    ('TIPO-CARNE', 'PEIXES-AGUA-DOCE'),
                                    ('TIPO-CARNE', 'AVES'),
                                    ('CARNE-BOVINA','Acém'),
									('CARNE-BOVINA','Alcatra'),
									('CARNE-BOVINA','Capa de filé'),
									('CARNE-BOVINA','Contra filé'),
									('CARNE-BOVINA','Coxão duro'),
									('CARNE-BOVINA','Coxão mole'),
									('CARNE-BOVINA','Cupim'),
									('CARNE-BOVINA','Filé de costela'),
									('CARNE-BOVINA','Filé-mignon'),
									('CARNE-BOVINA','Fraldinha'),
									('CARNE-BOVINA','Lagarto'),
									('CARNE-BOVINA','Maminha'),
									('CARNE-BOVINA','Músculo dianteiro'),
									('CARNE-BOVINA','Músculo traseiro'),
									('CARNE-BOVINA','Paleta'),
									('CARNE-BOVINA','Patinho'),
									('CARNE-BOVINA','Peito'),
									('CARNE-BOVINA','Pescoço'),
									('CARNE-BOVINA','Picanha'),
									('CARNE-BOVINA','Ponta de agulha'),
                                    ('CARNE-SUINO','Bisteca'),
									('CARNE-SUINO','Filé Mignon'),
									('CARNE-SUINO','Suã'),
									('CARNE-SUINO','Lombo'),
									('CARNE-SUINO','Maminha'),
									('CARNE-SUINO','Paleta'),
									('CARNE-SUINO','Papada'),
									('CARNE-SUINO','T-Bone'),
									('CARNE-SUINO','Lombo Inglês'),
									('CARNE-SUINO','Copa-lombo'),
									('CARNE-SUINO','Pancetta'),
									('CARNE-SUINO','Pernil'),
									('CARNE-SUINO','Ossobuco'),
									('CARNE-SUINO','Alcatra'),
									('CARNE-SUINO','Máscara'),
									('CARNE-SUINO','Joelho'),
									('CARNE-SUINO','Prime Rib'),
									('CARNE-SUINO','Barriga'),
									('CARNE-SUINO','Coxão duro'),
									('CARNE-SUINO','Pé Dianteiro'),
									('CARNE-SUINO','Fraldinha'),
									('CARNE-SUINO','Costela'),
									('CARNE-SUINO','Picanha'),
									('CARNE-SUINO','Rabo'),
									('CARNE-SUINO','Orelha'),
									('CARNE-SUINO','Ribeye'),
									('CARNE-SUINO','Carré'),
                                    ('PEIXE-AGUA-SALGADA', 'Agulha'),
									('PEIXE-AGUA-SALGADO', 'Anchova'),
									('PEIXE-AGUA-SALGADO', 'Atum'),
									('PEIXE-AGUA-SALGADO', 'Bacalhau'),
									('PEIXE-AGUA-SALGADO', 'Badejo'),
									('PEIXE-AGUA-SALGADO', 'Cavala'),
									('PEIXE-AGUA-SALGADO', 'Dourado '),
									('PEIXE-AGUA-SALGADO', 'Garoupa'),
									('PEIXE-AGUA-SALGADO', 'Linguado'),
									('PEIXE-AGUA-SALGADO', 'Manjuba'),
									('PEIXE-AGUA-SALGADO', 'Merluza'),
									('PEIXE-AGUA-SALGADO', 'Pargo'),
									('PEIXE-AGUA-SALGADO', 'Peixe-espada'),
									('PEIXE-AGUA-SALGADO', 'Pescada'),
									('PEIXE-AGUA-SALGADO', 'Polaca do Alasca'),
									('PEIXE-AGUA-SALGADO', 'Porquinho'),
									('PEIXE-AGUA-SALGADO', 'Robalo'),
									('PEIXE-AGUA-SALGADO', 'Salmão'),
									('PEIXE-AGUA-SALGADO', 'Sardinha'),
									('PEIXE-AGUA-DOCE', 'Carpa'),
									('PEIXE-AGUA-DOCE', 'Corvina'),
									('PEIXE-AGUA-DOCE', 'Curimbatá'),
									('PEIXE-AGUA-DOCE', 'Dourado de rio'),
									('PEIXE-AGUA-DOCE', 'Lambari'),
									('PEIXE-AGUA-DOCE', 'Matrinxã'),
									('PEIXE-AGUA-DOCE', 'Pacu'),
									('PEIXE-AGUA-DOCE', 'Panga'),
									('PEIXE-AGUA-DOCE', 'Pintado'),
									('PEIXE-AGUA-DOCE', 'Piramutaba'),
									('PEIXE-AGUA-DOCE', 'Pirarucu'),
									('PEIXE-AGUA-DOCE', 'Tambaqui'),
									('PEIXE-AGUA-DOCE', 'Tilápia'),
									('PEIXE-AGUA-DOCE', 'Traíra'),
									('PEIXE-AGUA-DOCE', 'Truta'),
									('PEIXE-AGUA-DOCE', 'Tucunaré'),
                                    ('AVES','Peito'),
									('AVES','Asas'),
									('AVES','coxa'),
									('AVES','Sobrecoxa'),
									('AVES','Miúdos'),
									('AVES','Coração');

																													
																				